name: NameRTS39
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.20
  - pip=24.2
  - setuptools=75.1.0
  - wheel=0.44.0
  - numpy=1.26.4
  - pandas=2.2.3
  - networkx=3.2.1
  - pip:
      - detect-indent==1.0.0
      - tree-sitter==0.23.2
      - tree-sitter-python==0.23.6
      - xxhash==3.5.0
